
set(CPP_TEMPLATE_PROJECT_NAME          sample_project)
set(CPP_TEMPLATE_PACKAGE_NAME          sample)
set(CPP_TEMPLATE_PACKAGE_VERSION       0.0.1)
set(CPP_TEMPLATE_PACKAGE_COMPATIBILITY AnyNewerVersion)
set(CPP_TEMPLATE_LIBRARY_NAME          sample)
