name: Build

on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  Spellcheck:
    timeout-minutes: 10
    runs-on: ubuntu-18.04
    container: 'ghcr.io/nontan-rh/cpp-template-ci-nodejs:20200919_1041'
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: script/cspell.sh
  Tidy:
    timeout-minutes: 10
    runs-on: ubuntu-18.04
    container: 'ghcr.io/nontan-rh/cpp-template-ci-clang:20200919_1041'
    steps:
      - uses: actions/checkout@v2
      - run: script/format.sh
      - run: git diff --exit-code
      - run: script/tidy.sh
  Linux:
    timeout-minutes: 10
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        image: ['clang', 'gcc']
    container: 'ghcr.io/nontan-rh/cpp-template-ci-${{ matrix.image }}:20200919_1041'
    steps:
      - uses: actions/checkout@v2
      - run: script/test.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=ON
      - run: script/test.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
      - run: script/build_consumer.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  Windows_MSVC:
    timeout-minutes: 10
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: script/test.sh -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug
      - run: script/test.sh -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release
      - run: script/build_consumer.sh -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release
  Windows_MinGW:
    timeout-minutes: 10
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: script/test.sh -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Debug
      - run: script/test.sh -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release
      - run: script/build_consumer.sh -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release
  macOS:
    timeout-minutes: 10
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: script/test.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=ON
      - run: script/test.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
      - run: script/build_consumer.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  Wasm:
    timeout-minutes: 10
    runs-on: ubuntu-18.04
    container: 'ghcr.io/nontan-rh/cpp-template-ci-emscripten:20200919_1041'
    steps:
      - uses: actions/checkout@v2
      - run: script/test_emscripten.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
      - run: script/test_emscripten.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
