name: Build

on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  timeout-minutes: 10
  runs-on: ubuntu-18.04
  run:
    shell: bash

env:
  DOCKER_IMAGE_REGISTRY: ${{ format('{0}/{1}', 'docker.pkg.github.com', github.repository) }}
  DOCKER_IMAGE_TAG: 20200919_1013 

jobs:
  Spellcheck:
    container: ${{ format('{0}/nodejs:{1}', env.DOCKER_IMAGE_REGISTRY, env.DOCKER_IMAGE_TAG) }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: script/cspell.sh
  Tidy:
    container: ${{ format('{0}/clang:{1}', env.DOCKER_IMAGE_REGISTRY, env.DOCKER_IMAGE_TAG) }}
    steps:
      - uses: actions/checkout@v2
      - run: script/format.sh
      - run: git diff --exit-code
      - run: script/tidy.sh
  Linux:
    strategy:
      matrix:
        image: ['clang', 'gcc']
    container: ${{ format('{0}/{1}:{2}', env.DOCKER_IMAGE_REGISTRY, matrix.image, env.DOCKER_IMAGE_TAG) }}
    steps:
      - uses: actions/checkout@v2
      - run: script/test.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=ON
      - run: script/test.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
      - run: script/build_consumer.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  Windows_MSVC:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: script/test.sh -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug
      - run: script/test.sh -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release
      - run: script/build_consumer.sh -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release
  Windows_MinGW:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: script/test.sh -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Debug
      - run: script/test.sh -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release
      - run: script/build_consumer.sh -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release
  macOS:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: script/test.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=ON
      - run: script/test.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
      - run: script/build_consumer.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  Wasm:
    container: ${{ format('{0}/emscripten:{1}', env.DOCKER_IMAGE_REGISTRY, env.DOCKER_IMAGE_TAG) }}
    steps:
      - uses: actions/checkout@v2
      - run: script/test_emscripten.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
      - run: script/test_emscripten.sh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
