name: Build CI Image

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy images and create a tag'
        default: 'false'

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
