name: Build CI Image

on:
  push:
    paths:
      - '.github/workflows/ci_image.yml'
      - 'docker/**.dockerfile'
      - 'script/build_docker_images.ps1'
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy images (true/false)'
        required: true
        default: 'false'

jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |-
          set -euxo pipefail

          docker_tag="$(date '+%Y%m%d_%H%M')"
          git_tag="image_${docker_tag}"

          printenv DOCKER_REGISTRY_PASSWORD | docker login "$DOCKER_REGISTRY_HOST" --username "$DOCKER_REGISTRY_USERNAME" --password-stdin
          pwsh script/build_docker_images.ps1 \
            -Registry "$DOCKER_REGISTRY_HOST/$DOCKER_REGISTRY_USERNAME" \
            -Prefix "$DOCKER_IMAGE_PREFIX" \
            -Tag "$docker_tag" \
            "-Push:\$$INPUTS_DEPLOY"
          if [ "$INPUTS_DEPLOY" = "true" ]; then
            git tag "$git_tag"
            git push origin "$git_tag"
          fi
        shell: bash
        env:
          INPUTS_DEPLOY: ${{ github.event.inputs.deploy || 'false' }}
          DOCKER_REGISTRY_HOST: ghcr.io
          DOCKER_REGISTRY_USERNAME: ${{ github.repository_owner }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.CR_PAT }}
          DOCKER_IMAGE_PREFIX: cpp-template-ci-
